### ISSUE TITLE
Specifying `--catalogurl [url]` results in Namespace error

### ISSUE THREAD

**Issue by carlashley** [munki/macadmin-scripts#10]
Pulled a fresh copy this morning and ran the command with the `--catalogurl [url]` argument and had a Namespace exception occur.

```
bash-3.2# ./installinstallmacos.py --catalogurl https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz --compress
Traceback (most recent call last):
  File "./installinstallmacos.py", line 528, in <module>
    main()
  File "./installinstallmacos.py", line 427, in main
    su_catalog_url = args.sucatalog_url
AttributeError: 'Namespace' object has no attribute 'sucatalog_url'
bash-3.2# ./installinstallmacos.py --compress --catalogurl https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
Traceback (most recent call last):
  File "./installinstallmacos.py", line 528, in <module>
    main()
  File "./installinstallmacos.py", line 427, in main
    su_catalog_url = args.sucatalog_url
AttributeError: 'Namespace' object has no attribute 'sucatalog_url'```

**Comment by gregneagle** [comment]
Thanks for reporting!
