### ISSUE TITLE
Non-Zero Exit Status: 35 (Catlina 10.15.2 Beta 2)

### ISSUE THREAD

**Issue by cybertunnel** [munki/macadmin-scripts#38]
**Command:**

`sudo ./installinstallmacos.py --catalogurl https://swscan.apple.com/content/catalogs/others/index-10.15customerseed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz --workdir ./macOS\ Installers/`

**STDOUT:**
```
Downloading https://swscan.apple.com/content/catalogs/others/index-10.15customerseed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz...
Downloading http://swcdn.apple.com/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/041-88800.English.dist...
Could not replicate https://swdist.apple.com/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/041-88800.English.dist: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'./macOS Installers/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/041-88800.English.dist', u'-z', u'./macOS Installers/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/041-88800.English.dist', 'https://swdist.apple.com/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/041-88800.English.dist']' returned non-zero exit status 35
Downloading http://swcdn.apple.com/content/downloads/41/23/061-26578-A_FF0C6M87LS/ylvl0phx6uy3i444qt9p57n8wz0xnylmd9/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/41/23/061-26578-A_FF0C6M87LS/ylvl0phx6uy3i444qt9p57n8wz0xnylmd9/061-26578.English.dist...
Downloading http://swcdn.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/061-26589.English.dist...
Could not replicate https://swdist.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/061-26589.English.dist: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'./macOS Installers/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/061-26589.English.dist', u'-z', u'./macOS Installers/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/061-26589.English.dist', 'https://swdist.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/061-26589.English.dist']' returned non-zero exit status 35
Downloading http://swcdn.apple.com/content/downloads/08/44/041-90855-A_452WLVQACP/mzfvoi59bljh3w4w4lvwenfk0r1a2f7212/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/08/44/041-90855-A_452WLVQACP/mzfvoi59bljh3w4w4lvwenfk0r1a2f7212/041-90855.English.dist...
Could not replicate https://swdist.apple.com/content/downloads/08/44/041-90855-A_452WLVQACP/mzfvoi59bljh3w4w4lvwenfk0r1a2f7212/041-90855.English.dist: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'./macOS Installers/content/downloads/08/44/041-90855-A_452WLVQACP/mzfvoi59bljh3w4w4lvwenfk0r1a2f7212/041-90855.English.dist', u'-z', u'./macOS Installers/content/downloads/08/44/041-90855-A_452WLVQACP/mzfvoi59bljh3w4w4lvwenfk0r1a2f7212/041-90855.English.dist', 'https://swdist.apple.com/content/downloads/08/44/041-90855-A_452WLVQACP/mzfvoi59bljh3w4w4lvwenfk0r1a2f7212/041-90855.English.dist']' returned non-zero exit status 35
Downloading http://swcdn.apple.com/content/downloads/06/50/041-91758-A_M8T44LH2AW/b5r4og05fhbgatve4agwy4kgkzv07mdid9/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/06/50/041-91758-A_M8T44LH2AW/b5r4og05fhbgatve4agwy4kgkzv07mdid9/041-91758.English.dist...
Downloading http://swcdn.apple.com/content/downloads/30/26/061-44345-A_KESM6DQZ3B/44cdw7ri5cg3bi4ko4pox21ce655pu4f86/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/30/26/061-44345-A_KESM6DQZ3B/44cdw7ri5cg3bi4ko4pox21ce655pu4f86/061-44345.English.dist...
Could not replicate https://swdist.apple.com/content/downloads/30/26/061-44345-A_KESM6DQZ3B/44cdw7ri5cg3bi4ko4pox21ce655pu4f86/061-44345.English.dist: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'./macOS Installers/content/downloads/30/26/061-44345-A_KESM6DQZ3B/44cdw7ri5cg3bi4ko4pox21ce655pu4f86/061-44345.English.dist', u'-z', u'./macOS Installers/content/downloads/30/26/061-44345-A_KESM6DQZ3B/44cdw7ri5cg3bi4ko4pox21ce655pu4f86/061-44345.English.dist', 'https://swdist.apple.com/content/downloads/30/26/061-44345-A_KESM6DQZ3B/44cdw7ri5cg3bi4ko4pox21ce655pu4f86/061-44345.English.dist']' returned non-zero exit status 35
Downloading http://swcdn.apple.com/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/041-83630.English.dist...
Could not replicate https://swdist.apple.com/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/041-83630.English.dist: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'./macOS Installers/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/041-83630.English.dist', u'-z', u'./macOS Installers/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/041-83630.English.dist', 'https://swdist.apple.com/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/041-83630.English.dist']' returned non-zero exit status 35
Downloading http://swcdn.apple.com/content/downloads/16/53/061-45871-A_X87T6CILQ4/d3zi0ag6voifghf4jwvkl0tfosa0b2j86r/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/16/53/061-45871-A_X87T6CILQ4/d3zi0ag6voifghf4jwvkl0tfosa0b2j86r/061-45871.English.dist...
Could not replicate https://swdist.apple.com/content/downloads/16/53/061-45871-A_X87T6CILQ4/d3zi0ag6voifghf4jwvkl0tfosa0b2j86r/061-45871.English.dist: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'./macOS Installers/content/downloads/16/53/061-45871-A_X87T6CILQ4/d3zi0ag6voifghf4jwvkl0tfosa0b2j86r/061-45871.English.dist', u'-z', u'./macOS Installers/content/downloads/16/53/061-45871-A_X87T6CILQ4/d3zi0ag6voifghf4jwvkl0tfosa0b2j86r/061-45871.English.dist', 'https://swdist.apple.com/content/downloads/16/53/061-45871-A_X87T6CILQ4/d3zi0ag6voifghf4jwvkl0tfosa0b2j86r/061-45871.English.dist']' returned non-zero exit status 35
 #    ProductID    Version    Build   Post Date  Title
 1    041-91758    10.13.6    17G66  2019-10-19  macOS High Sierra
Traceback (most recent call last):
  File "./installinstallmacos.py", line 596, in <module>
    main()
  File "./installinstallmacos.py", line 527, in main
    product_info[product_id]['BUILD'],
KeyError: u'BUILD'```

**Comment by cybertunnel** [comment]
This might have been related to my machine running customer seed, and not specified it in the command args. Testing now and will report back.

**Comment by cybertunnel** [comment]
Nope, still get `Could not replicate https://swdist.apple.com/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/InstallESDDmg.pkm: Command '[u'/usr/bin/curl', u'-sfL', u'--create-dirs', u'-o', u'./macOS Installers/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/InstallESDDmg.pkm', 'https://swdist.apple.com/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/InstallESDDmg.pkm']' returned non-zero exit status 35`

**Comment by gregneagle** [comment]
"Could not replicate" could be (and almost certainly _is_) caused by local network issues.

Works here as expected:

```
# sudo ./installinstallmacos.py --catalogurl https://swscan.apple.com/content/catalogs/others/index-10.15customerseed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz 
Downloading https://swscan.apple.com/content/catalogs/others/index-10.15customerseed-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz...
Downloading http://swcdn.apple.com/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/041-88800.English.dist...
Downloading http://swcdn.apple.com/content/downloads/41/23/061-26578-A_FF0C6M87LS/ylvl0phx6uy3i444qt9p57n8wz0xnylmd9/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/41/23/061-26578-A_FF0C6M87LS/ylvl0phx6uy3i444qt9p57n8wz0xnylmd9/061-26578.English.dist...
Downloading http://swcdn.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/061-26589.English.dist...
Downloading http://swcdn.apple.com/content/downloads/08/44/041-90855-A_452WLVQACP/mzfvoi59bljh3w4w4lvwenfk0r1a2f7212/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/08/44/041-90855-A_452WLVQACP/mzfvoi59bljh3w4w4lvwenfk0r1a2f7212/041-90855.English.dist...
Downloading http://swcdn.apple.com/content/downloads/06/50/041-91758-A_M8T44LH2AW/b5r4og05fhbgatve4agwy4kgkzv07mdid9/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/06/50/041-91758-A_M8T44LH2AW/b5r4og05fhbgatve4agwy4kgkzv07mdid9/041-91758.English.dist...
Downloading http://swcdn.apple.com/content/downloads/30/26/061-44345-A_KESM6DQZ3B/44cdw7ri5cg3bi4ko4pox21ce655pu4f86/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/30/26/061-44345-A_KESM6DQZ3B/44cdw7ri5cg3bi4ko4pox21ce655pu4f86/061-44345.English.dist...
Downloading http://swcdn.apple.com/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/61/56/041-83630-A_8RCIBB415Y/7jqh3nh97ood2mjej7hdgpx7fgh5c3fi9g/041-83630.English.dist...
Downloading http://swcdn.apple.com/content/downloads/16/53/061-45871-A_X87T6CILQ4/d3zi0ag6voifghf4jwvkl0tfosa0b2j86r/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/16/53/061-45871-A_X87T6CILQ4/d3zi0ag6voifghf4jwvkl0tfosa0b2j86r/061-45871.English.dist...
 #    ProductID    Version    Build   Post Date  Title
 1    041-91758    10.13.6    17G66  2019-10-19  macOS High Sierra
 2    041-88800    10.14.4  18E2034  2019-10-23  macOS Mojave
 3    061-26589    10.14.6   18G103  2019-10-14  macOS Mojave
 4    041-83630    10.15.1    19B88  2019-10-29  macOS Catalina
 5    061-45871    10.15.1  19B2106  2019-11-13  macOS Catalina
 6    041-90855    10.13.5   17F66a  2019-10-23  Install macOS High Sierra Beta
 7    061-26578    10.14.5  18F2059  2019-10-14  macOS Mojave
 8    061-44345    10.15.2   19C39d  2019-11-15  macOS Catalina Beta

Choose a product to download (1-8): 
```

**Comment by cybertunnel** [comment]
So the age old "Turn it off, and turn it back on" strikes again... 🤦‍♂
