### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 121: ordinal not in range(128)

### ISSUE THREAD

**Issue by Wartz** [munki/macadmin-scripts#63]
```
installinstallmacos.py - get macOS installers from the Apple software catalog

This Mac:
Model Identifier : iMac18,2
Bridge ID        : None
Board ID         : Mac-77F17D7DA9285301
OS Version       : 10.13.4
Build ID         : 17E202

Traceback (most recent call last):
  File "installinstallmacos.py", line 1186, in <module>
    main()
  File "installinstallmacos.py", line 827, in main
    catalog, args.workdir, ignore_cache=args.ignore_cache
  File "installinstallmacos.py", line 590, in os_installer_product_info
    board_ids = get_board_ids(dist_path)
  File "installinstallmacos.py", line 486, in get_board_ids
    if "boardIds" in line:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 121: ordinal not in range(128)
```

**Comment by gregneagle** [comment]
That's not my script -- it does not have output like that. Perhaps you are using Graham Pugh's version?

**Comment by Wartz** [comment]
Yup - my bad.
