### ISSUE TITLE
Unable to retrieve Build numbers

### ISSUE THREAD

**Issue by mikedowler** [munki/macadmin-scripts#72]
I have updated to the current version.
Running installinstallmacos.py, I see the following errors in the output (last three lines shown), then I get the choices with all Build numbers listed as UNKNOWN:
```
Downloading http://swcdn.apple.com/content/downloads/37/41/001-04366/a6boefh8b6bee4k2x6v5lwyfjr7od2ica3/InstallAssistantAuto.smd...
Downloading https://swdist.apple.com/content/downloads/37/41/001-04366/a6boefh8b6bee4k2x6v5lwyfjr7od2ica3/001-04366.English.dist...
Invalid XML in ./content/downloads/37/41/001-04366/a6boefh8b6bee4k2x6v5lwyfjr7od2ica3/001-04366.English.dist
 #      ProductID    Version    Build   Post Date  Title
 1      001-04366    10.15.4  UNKNOWN  2020-05-04  macOS Catalina
 2      041-91758    10.13.6  UNKNOWN  2019-10-19  macOS High Sierra
 3      041-88800    10.14.4  UNKNOWN  2019-10-23  macOS Mojave
 4      061-26589    10.14.6  UNKNOWN  2019-10-14  macOS Mojave
 5      001-51042    10.15.7  UNKNOWN  2020-09-24  macOS Catalina
 6      001-36735    10.15.6  UNKNOWN  2020-08-06  macOS Catalina
 7      061-86291    10.15.3  UNKNOWN  2020-03-23  macOS Catalina
 8      041-90855    10.13.5  UNKNOWN  2019-10-23  Install macOS High Sierra Beta
 9      061-26578    10.14.5  UNKNOWN  2019-10-14  macOS Mojave
10      001-36801    10.15.6  UNKNOWN  2020-08-12  macOS Catalina
```

Running one of the options then fails with the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/installinstallmacos.py", line 629, in <module>
    main()
  File "/usr/local/bin/installinstallmacos.py", line 583, in main
    product_info[product_id]['BUILD']))
KeyError: u'BUILD'
```

**Comment by grahampugh** [comment]
@mikedowler did you delete the `./content` folder before re-running?

**Comment by mikedowler** [comment]
@grahampugh - that fixed it.  my bad!
